modules:
  - noisyconv_pyt
batchsz: 50
basedir: trec-pyt
preproc:
  mxlen: 100
  rev: false
  clean: true
backend: pytorch
dataset: trec
loader:
  reader_type: default
unif: 0.25
model:
  model_type: noisyconv
  filtsz: [3]
  cmotsz: 100
  dropout: 0.5

features:
  - name: word
    vectorizer:
      type: token1d
      transform: baseline.lowercase
    embeddings:
      label: w2v-gn
train:
  fit_func: train-noisy-model
  model_base: ./models/trec
  epochs: 30
  optim: adadelta
  eta: 1.0
  early_stopping_metric: acc
  nm: True
  noiselvl: 0.5
  noisetyp: uni
  nmpenality: 0.1
  nminit: identity
  nmscale: 6
  verbose:
    console: True
    file: sst2-cm.csv

